[package]
name = "hero8"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.5"
rand = "0.8.5"
uuid = "1.8.0"
tokio = { version = "1.37.0", features = ["full"] }
log = "0.4.21"
env_logger = "0.11.3"
thiserror = "2.0.12"
